version: '2'
services:
  backend-app:
    image: backend
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://backend-postgresql:5432/backend
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://backend-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://backend-elasticsearch:9200
    ports:
      - 8080:8080
  backend-postgresql:
    extends:
      file: postgresql.yml
      service: backend-postgresql
  backend-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: backend-elasticsearch
